set search_path to consorzio;

-- Modifica temporanea per permettere l'inserimento degli ID generati nel CSV
ALTER TABLE banca ALTER COLUMN codiceBanca SET GENERATED BY DEFAULT;
ALTER TABLE filiale ALTER COLUMN codiceFiliale SET GENERATED BY DEFAULT;
ALTER TABLE impiegato ALTER COLUMN idImpiegato SET GENERATED BY DEFAULT;
ALTER TABLE conto ALTER COLUMN numeroConto SET GENERATED BY DEFAULT;
ALTER TABLE interfaccia ALTER COLUMN idInterfaccia SET GENERATED BY DEFAULT;
ALTER TABLE operazione ALTER COLUMN idOperazione SET GENERATED BY DEFAULT;

-- Disabilita temporaneamente i trigger per evitare controlli e side-effect sul caricamento bulk dei dati storici
ALTER TABLE presta_servizio_in DISABLE TRIGGER ALL;
ALTER TABLE operazione DISABLE TRIGGER ALL;

-- Utilizzo \copy per caricamento client-side.
-- NULL '' : le celle vuote nel CSV vengono interpretate come NULL (non come stringa vuota).
\copy banca FROM '${DATA_DIR}/banca.csv' WITH (FORMAT csv, NULL '')
\copy filiale FROM '${DATA_DIR}/filiale.csv' WITH (FORMAT csv, NULL '')
\copy persona FROM '${DATA_DIR}/persona.csv' WITH (FORMAT csv, NULL '')
\copy cliente FROM '${DATA_DIR}/cliente.csv' WITH (FORMAT csv, NULL '')
\copy impiegato FROM '${DATA_DIR}/impiegato.csv' WITH (FORMAT csv, NULL '')
\copy conto FROM '${DATA_DIR}/conto.csv' WITH (FORMAT csv, NULL '')
\copy intestato_a FROM '${DATA_DIR}/intestato_a.csv' WITH (FORMAT csv, NULL '')
\copy presta_servizio_in FROM '${DATA_DIR}/presta_servizio_in.csv' WITH (FORMAT csv, NULL '')
\copy cartaBancomat FROM '${DATA_DIR}/cartaBancomat.csv' WITH (FORMAT csv, NULL '')
\copy interfaccia FROM '${DATA_DIR}/interfaccia.csv' WITH (FORMAT csv, NULL '')
\copy operazione FROM '${DATA_DIR}/operazione.csv' WITH (FORMAT csv, NULL '')

-- Riabilita i trigger dopo il caricamento bulk dei dati
ALTER TABLE presta_servizio_in ENABLE TRIGGER ALL;
ALTER TABLE operazione ENABLE TRIGGER ALL;

-- Ripristino dei constraint IDENTITY
ALTER TABLE banca ALTER COLUMN codiceBanca SET GENERATED ALWAYS;
ALTER TABLE filiale ALTER COLUMN codiceFiliale SET GENERATED ALWAYS;
ALTER TABLE impiegato ALTER COLUMN idImpiegato SET GENERATED ALWAYS;
ALTER TABLE conto ALTER COLUMN numeroConto SET GENERATED ALWAYS;
ALTER TABLE interfaccia ALTER COLUMN idInterfaccia SET GENERATED ALWAYS;
ALTER TABLE operazione ALTER COLUMN idOperazione SET GENERATED ALWAYS;

-- Sincronizzazione delle sequenze con il valore massimo inserito per evitare collisioni future
SELECT setval(pg_get_serial_sequence('banca', 'codicebanca'), (SELECT MAX(codiceBanca) FROM banca));
SELECT setval(pg_get_serial_sequence('filiale', 'codicefiliale'), (SELECT MAX(codiceFiliale) FROM filiale));
SELECT setval(pg_get_serial_sequence('impiegato', 'idimpiegato'), (SELECT MAX(idImpiegato) FROM impiegato));
SELECT setval(pg_get_serial_sequence('conto', 'numeroconto'), (SELECT MAX(numeroConto) FROM conto));
SELECT setval(pg_get_serial_sequence('interfaccia', 'idinterfaccia'), (SELECT MAX(idInterfaccia) FROM interfaccia));
SELECT setval(pg_get_serial_sequence('operazione', 'idoperazione'), (SELECT MAX(idOperazione) FROM operazione));