---
title: "lezione 6"
author: "Mameli"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Esercizio 1
```{r}
# Calcolare P(X=0) dove X~Binom(n,p)
n = 52
p = 0.013

#P(X=0)
dbinom(0,size=n,prob=p)
```
```{r}
#P(X<=2)=P(X=0)+P(X=1)+P(X=2)
dbinom(0,n,p)+dbinom(1,n,p)+dbinom(2,n,p)
```
*  oppure

```{r}
sum(dbinom(0:2,n,p))
```

* oppure

```{r}
pbinom(2,n,p)
```
## Funzione di probabilità
```{r}
x = 0:52
plot(x,dbinom(x,n,p),type="h",col="blue",xlab="x",ylab="Probabilità")
```

## Funzione di ripartizione
```{r}
x = 0:52
plot(x,pbinom(x,n,p),type="s",col="blue",xlab="x",ylim=c(0,1),xlim=c(-5,52))
segments(-5,0,0,0,col="blue")
```

## Esercizio 2
```{r}
#X~Pois(lambda) vogliamo caloclare P(X<=2)
lambda=3.8
ppois(2,lambda)
sum(dpois(0:2,lambda))
```
## Esercizio 3
```{r}
# X~Geom(p) X=conta il numero di insuccessi necessari al primo successo
p = 0.02# probabilità di successo, prob di essere difettoso
x=9 # numero di fallimenti prima di arrivare al successo
p*(1-p)^x

dgeom(x,p)
```
## Esercizio 4

```{r}
#X=Peso dei bovini appertenenti all'intervallo 300-400Kg
#X~U(300,400)

#P(310<=X<=350)

punif(350,300,400)-punif(310,300,400)
```
## Densità dell'uniforme tra 300 e 400
```{r}
curve(dunif(x,300,400),300,400,col="red",ylab="densità",xlab="Peso")
```
## Estrazione di 15 bovini con un peso compreso tra 300 e 400 Kg
```{r}
set.seed(100)
runif(15,300,400)
```
## Esercizio 5
```{r}
# X = tempo in minuti tra apertura sportello e arrivo primo utente
# lambda=1/media
#X~Exp(lambda)

lambda = 1/4

#P(X>10)=1-P(X<=10)

1-pexp(10, rate = lambda)

``` 
## Esercizio 6
```{r}
#X=Voto di statistica X~N(mu=23,sigma^2=9)
# P(21<=X<=25)
mu=23
sigma = sqrt(9)
pnorm(25, mean = mu, sd = sigma)-pnorm(21, mean = mu, sd = sigma)
```

```{r}
library(tigerstats)

pnormGC(c(21,25),mean=mu,sd=sigma,region="between",graph = T)
```

```{r}
#P(X>28)

1-pnorm(28,mu,sigma)
```
## oppure
```{r}
pnormGC(28,mu,sigma,graph=T,region="above")
```
## quantile d'ordine 95%
```{r}
qnorm(0.95,mu,sigma)
```
## funzione di densità della normale
```{r}
curve(dnorm(x,mu,sigma),mu-3*sigma,mu+3*sigma,col="red",ylab="densità",xlab="Voto")
```

