---
title: "lezione 10"
author: "Mameli"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# File Test1_es
##Esercizio 2
```{r}
penicillina <- read.csv("C:/Users/Utente/Downloads/penicillina.txt", sep="")
attach(penicillina)
```
```{r}
n = nrow(penicillina)
(phat= length(Rid_Temp[Rid_Temp=="S"])/n)
p0 = 0.6
(z_oss=(phat-p0)/sqrt(p0*(1-p0)/n))
```
```{r}
alpha = 0.05
(z_alpha=qnorm(alpha,lower.tail = F))
```

```{r}
#p_value=P(Z>z_oss)
(p_value = 1-pnorm(z_oss))
```

```{r}
numero_successi = length(Rid_Temp[Rid_Temp=="S"])
prop.test(numero_successi,n,p=p0,correct = F,alternative = "greater")
```

```{r}
z_oss^2
```
## Esercizio 1
```{r}
siero <- read.csv("C:/Users/Utente/Downloads/siero.txt", sep="")
attach(siero)
```

```{r}
boxplot(Siero)
```

```{r}
summary(Siero)
```

```{r}
library(moments)
skewness(Siero)
```
```{r}
kurtosis(Siero)
```
```{r}
library(car)
qqPlot(Siero)
```
```{r}
new_siero=log(Siero)
```

```{r}
qqPlot(new_siero)
```

```{r}
t.test(new_siero,mu=log(0.4),alternative = "greater")
```
```{r}
alpha=0.05
n=length(new_siero)
(t_alpha=qt(alpha,n-1,lower.tail = F))
```

# Esercizi Test 2 parte
## Esercizio 1
```{r}
temperatura <- read.delim("C:/Users/Utente/Downloads/temperatura.txt")
attach(temperatura)
```

```{r}
tapply(Temperatura, Sesso, summary)
```
```{r}
boxplot(Temperatura~Sesso)
```

```{r}
par(mfrow=c(1,2))
qqPlot(Temperatura[Sesso=="D"])
qqPlot(Temperatura[Sesso=="U"])
```

```{r}
table(Sesso)
```
## Test sulle varianze

```{r}
alpha=0.05
n1 = length(Temperatura[Sesso=="D"])
n2 = length(Temperatura[Sesso=="U"])
```


```{r}
(f_oss=var(Temperatura[Sesso=="D"])/var(Temperatura[Sesso=="U"]))
```
```{r}
(f_alpha_mezzi = qf(alpha/2,n1-1,n2-1,lower.tail = F))
```


```{r}
(f_1_meno_alpha_mezzi= qf(1-alpha/2,n1-1,n2-1,lower.tail = F))
```
```{r}
2*(min(pf(f_oss,n1-1,n2-1),1-pf(f_oss,n1-1,n2-1)))
```

```{r}
temp_d=Temperatura[Sesso=="D"]
temp_u=Temperatura[Sesso=="U"]


var.test(temp_d,temp_u)
```
## Test sulle medie
```{r}
n1 = length(Temperatura[Sesso=="D"])
n2 = length(Temperatura[Sesso=="U"])
(s2_p = ((n1-1)*var(temp_d)+(n2-1)*var(temp_u))/(n1+n2-2) )
```
```{r}
(t_oss=(mean(temp_d)-mean(temp_u))/sqrt(s2_p*(1/n1+1/n2)))
```
```{r}
(t_alpha_mezzi=qt(alpha/2,n1+n2-2,lower.tail = F))
```
```{r}
(p_value=2*min(pt(t_oss,n1+n2-2),1-pt(t_oss,n1+n2-2)))
```
```{r}
t.test(temp_d,temp_u,mu=0,var.equal = T)
```
## Esercizio 2
```{r}
saturazione <- read.delim("C:/Users/Utente/Downloads/saturazione.txt")
attach(saturazione)
```


```{r}
D=Pos-Osm
qqPlot(D)

```

```{r}
(d_oss=mean(D)/(sd(D)/sqrt(length(D))))
```

```{r}
(t_alpha_mezzi=qt(alpha,length(D)-1,lower.tail = F))
```
```{r}
(p_value=2*min(pt(d_oss,length(D)-1),1-pt(d_oss,length(D)-1)))
```
```{r}
t.test(Pos,Osm,mu=0,paired=T)
```

